---
title: "Explore fire data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Create a table summarizing data layers within each MTBS fire. 
Layers were assembled and reduced in Google Earth Engine: 

- 

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Install packages
library(sf) 
library(here)
library(dplyr) 
library(kableExtra)
library(ggplot2)
library(tidyr)
library(ggrepel)
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
# read shapefile where each row describes one fire 


# MTBS fires on USFS land, 200km from NIWO, within NEON domain 13
#      Fig 1 height: 8, Fig 4 height: 10
#fire_filename <- here::here("data/fire_stats_test.geojson")

# MTBS fires on USFS land, within the Southern Rockies EPA Level III ecoregion
#      Fig 1 height: 16, Fig 4 height: 16
#fire_filename <- here::here("data/fires_sRockiesEcoregion_USFS.geojson")

# MTBS fires within the Southern Rockies EPA Level III ecoregion
#      Fig 1 height: 24, Fig 4 height: 30
#fire_filename <- here::here("data/fires_sRockiesEcoregion.geojson")

# MTBS fires on USFS land, 200km from NIWO
#fire_filename <- here::here("data/fires_MTBS_local.geojson")

# FIRED fires on USFS land, 200km from NIWO
# Is there a way to get a fire's name from the FIRED data? 
#fire_filename <- here::here("data/fires_FIRED_local.geojson")

# MTBS fires <200km from NIWO, with forest cover, addding in GEDI cover 
fire_filename <- here::here("data/fires_stats_20210312.geojson")



# NAME OF CURRENT DATA SET OR ITERATION
# used to name output figures
out_label <- "MTBS_local_with_GEDI"



# Set figure height and width for Rmd html output
figHeight <- 10
figWidth <- 10



# read the fire data
fire_df <- sf::st_read(fire_filename)

# adjust the data type and/or precision of some fields
fire_df$id <- as.character(fire_df$id)     # Fire name 
fire_df$Acres <- as.integer(fire_df$Acres) # Fire size [acres]
fire_df$gedi_coverage <- round(as.numeric(as.character(fire_df$lodgepole)) * 100, digits = 1) # Percent GEDI pixels in fire perimeter
fire_df$lodgepole <- round(as.numeric(as.character(fire_df$lodgepole)) * 100, digits = 1)     # Percent lodgepole 
fire_df$ponderosa <- round(as.numeric(as.character(fire_df$ponderosa)) * 100, digits = 1)     # Percent ponderosa pine 
fire_df$spruceFir <- round(as.numeric(as.character(fire_df$spruceFir)) * 100, digits = 1)     # Percent spruce/fir 
fire_df$disturbed_burned <- round(as.numeric(as.character(fire_df$disturbed_burned)) * 100, digits = 1) # Percent burned
fire_df$disturbed_unspecific <- round(as.numeric(as.character(fire_df$disturbed_unspecific)) * 100, digits = 1) # Percent disturbed
#fire_df$disturbed_logged <- round(as.numeric(as.character(fire_df$disturbed_logged)) * 100, digits = 1)
#fire_df$regenerating_disturbed <- round(as.numeric(as.character(fire_df$regenerating_disturbed)) * 100, digits = 1)
#fire_df$regenerating_harvested <- round(as.numeric(as.character(fire_df$regenerating_harvested)) * 100, digits = 1)
```


```{r}
# how many fires in this data set? 
message("# of fires in dataset: ")
message(nrow(fire_df))

# create output directory for figures
if(!dir.exists(here::here("figures"))){
  dir.create(here::here("figures"))
}
```


```{r, message=FALSE, warning=FALSE}

# create a table to summarize attributes of interest per fire 
fire_table <- as.data.frame(fire_df) %>% 
  # select columns of interest
  dplyr::select(Fire_Name, Year, Acres, gedi_coverage, lodgepole, ponderosa, spruceFir, disturbed_burned, disturbed_unspecific, 
                #disturbed_logged, regenerating_disturbed, regenerating_harvested
                ) %>%
  # reorder the rows based on multiple variables 
  dplyr::arrange(desc(gedi_coverage), desc(lodgepole), desc(ponderosa), desc(spruceFir), desc(disturbed_burned)) %>%
  # rename the columns for interpretation
  dplyr::rename("Fire Name" = Fire_Name, 
                "Year" = Year,
                "Acres" = Acres,
                "GEDI %" = gedi_coverage,
                "Lodgepole %" = lodgepole,
                "Ponderosa %" = ponderosa,
                "Spruce Fir %" = spruceFir,
                "Disturbed Burned %" = disturbed_burned,
                "Disturbed Unspecified %" = disturbed_unspecific,
                #"Disturbed Logged %" = disturbed_logged,
                #"Regenerating Disturbed %" = regenerating_disturbed,
                #"Regenerating Harvested %" = regenerating_harvested
                ) 

# add a categorical column with dominant forest type 
temp <- fire_df %>% 
  dplyr::select(Fire_Name, lodgepole, ponderosa, spruceFir) %>% 
  tidyr::gather(major_forest_type, forest_percent, lodgepole:spruceFir) %>% 
  dplyr::group_by(Fire_Name) %>% 
  dplyr::slice(which.max(forest_percent)) %>% 
  dplyr::select(Fire_Name, major_forest_type) %>% 
  st_set_geometry(NULL)
fire_df <- fire_df %>% 
  dplyr::left_join(temp)
remove(temp)



kableExtra::kable(fire_table) %>%
  kableExtra::kable_styling(bootstrap_options = "striped", 
                            full_width = F, 
                            position = "left")

```


```{r}
# count number of fires with each dominant forest type 
kableExtra::kable(table(fire_df$major_forest_type),
                  col.names = c("Dominant forest type", "# of fire events")) %>%
  kableExtra::kable_styling(bootstrap_options = "striped", 
                            full_width = F, 
                            position = "left")
```


# Explore the fire data


## Map 

```{r, fig.height=9, fig.width=9, message=FALSE, warning=FALSE}
library(leaflet)
library(rgdal)
library(geojsonio)

# read geojson file for mapping with leaflet
fire_gjson <- rgdal::readOGR(fire_filename)

# add a column with fire perimeter centroid point locations for map labels
fire_df$centroid_lon <- NA
fire_df$centroid_lat <- NA
fire_df$centroid_label <- NA
for (i in 1:nrow(fire_df)){
  # create popup label using fire name and year
  content <- paste(sep = "<br/>",
    fire_df$Fire_Name[i], fire_df$Year[i])
  print(content)
  fire_df$centroid_label[i] <- content
  
  # get lon, lat coordinates of geometry centroid  
  fire_df$centroid_lon[i] <- st_centroid(fire_df$geometry[i])[[1]][1]
  fire_df$centroid_lat[i] <- st_centroid(fire_df$geometry[i])[[1]][2]
}


# color palette
pal <- colorNumeric(
  palette = "viridis",
  domain = fire_gjson$Year
)

# map the fire polygons
map <- leaflet(fire_gjson) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.7,
    color = ~pal(Year)
  ) %>%
  addLegend("bottomright", pal = pal, values = ~Year,
    title = "Fire Year",
    # get rid of the comma in years (1,990 becomes 1990) for legend entries
    labFormat = labelFormat(big.mark = ''),
    opacity = 1
  ) %>% 
  # set base map type
  addProviderTiles(providers$CartoDB.Positron) 

# Icons 
icons <- makeAwesomeIcon(
  icon = "fire",
  iconColor = "orange",
  library = "fa",
  markerColor = "gray"
)


# Add Fire Name popup labels to each polygon centroid
  map <- map %>%
    #addMarkers(lng = fire_df$centroid_lon, 
    addAwesomeMarkers(lng = fire_df$centroid_lon,
               lat = fire_df$centroid_lat, 
               icon=icons,
               popup = fire_df$centroid_label)

  # change icon width and height using makeIcon? 
  # check out CircleMarkers? 

# display map
map

```



## Fire timeline 

```{r fig1, fig.height = figHeight, fig.width = figWidth}

# calculate minimum and maximum fire years
year_min <- min(fire_df$Year)
year_max <- max(fire_df$Year)

# set forest type colors for the figures
                       # lodgepole  ponderosa  spruceFir
#forest_type_colors <- c("#005a32", "#74c476", "#e5f5e0") 
forest_type_colors <- c("#04663B", "#41ab5d", "#c7e9c0")


# reorder the rows based on year
fire_df <- fire_df %>% 
  dplyr::arrange(desc(Year)) 

# calculate point size - scaled relatively by fire size
tmp <- log(fire_df$Acres / max(fire_df$Acres))
tmp <- tmp + abs(min(tmp)) + 1.25

# create timeline figure 
ggplot(fire_df) + 
  geom_point(aes(x = reorder(Fire_Name, Year), y = Year, 
                 # color points based on dominant forest type
                 fill = major_forest_type), 
             # add a black outline around each point
             color = "black", shape=21, 
             # size of each point, thickness of outline
             size = tmp, 
             stroke = 0.3) + 
  scale_y_continuous(breaks = seq(year_min, year_max, by = 4)) + 
  labs(title = "Fire Event Timeline", y = "Year", x = "Fire Name\n",
       fill = "Dominant forest type") + 
  # Put fire name on Y axis, year on X axis
  coord_flip() + 
  # set the point fill colors using hex codes 
  scale_fill_manual(values = forest_type_colors,
                    labels = c("Lodgepole pine", "Ponderosa pine", "Spruce/Fir")) + 
  # set the point size in legend 
  guides(fill = guide_legend(override.aes = list(size=4))) + 
  # clean theme for plot with white background
  theme_bw() 

# Save figure to file
ggsave(filename = (here::here(file.path("figures",paste0(out_label,"-fire_timeline.png")))),
       width = 8, height = 6)
```


## Fire year histogram

```{r message=FALSE, warning=FALSE, fig.align="center"}

hist_year_title <- paste("Histogram: Fire Years,", year_min, "-", year_max)

# create histogram, fire count per year.
# color the bars based on the dominant forest type of each fire event. 
ggplot(fire_df, aes(x=Year, fill = major_forest_type)) + 
  geom_histogram(binwidth=1, color="black", 
                 # set the outline thickness and bar transparency. 
                 size = 0.2, alpha=0.9) + 
  labs(title = hist_year_title, y = "Count", fill = "Dominant forest type") + 
  # x axis label years from min to max year in increments of 4
  scale_x_continuous(breaks = seq(year_min, year_max, by = 4)) + 
  # set color scale of the dominant forest types
  scale_fill_manual(values= forest_type_colors,
                    labels = c("Lodgepole pine", "Ponderosa pine", "Spruce/Fir")) + 
  theme_bw()

# Save figure to file
ggsave(filename = (here::here(file.path("figures",paste0(out_label,"-fire_hist_years.png")))),
       width = 7, height = 5)
```

## Fire size histogram

```{r message=FALSE, warning=FALSE, fig.align="center"}
# color the bars based on the dominant forest type of each fire event. 
           # convert from Acres to Hectares? * 0.404686
ggplot(fire_df, aes(x = Acres * 0.404686)) + 
  geom_histogram(aes(fill = major_forest_type), color="black", 
                 # set the outline thickness and bar transparency. 
                 size = 0.2, alpha=0.9) + 
  labs(title = "Histogram: Fire Size", y = "Count", x = "Size [Hectares]",
       fill = "Dominant forest type") + 
  # set color scale of the dominant forest types
  scale_fill_manual(values = forest_type_colors,
                    labels = c("Lodgepole pine", "Ponderosa pine", "Spruce/Fir")) + 
  theme_bw()

# Save figure to file
ggsave(filename = (here::here(file.path("figures",paste0(out_label,"-fire_hist_size.png")))),
       width = 7, height = 5)
```

## Fire size as a function of year 

```{r, fig.height = 10, fig.width = 10}
ggplot(fire_df, aes(x=Year, y=Acres * 0.404686 , 
                    log="y", label = Fire_Name)) + 
  geom_point(aes(# color points based on dominant forest type
                 fill = major_forest_type), 
             # add a black outline around each point
             color = "black", shape=21, 
             # size of each point, thickness of outline
             size = 4, stroke = 0.5) + 
  labs(title = "Fire size vs year", 
       y = "Hectares [log transformed]", 
       fill = "Dominant forest type") + 
  # log transform the y axis to space out the points more 
  scale_y_continuous(trans='log2') + 
  scale_x_continuous(breaks = seq(year_min, year_max, by = 4)) + 
  scale_fill_manual(values = forest_type_colors,
                    labels = c("Lodgepole pine", "Ponderosa pine", "Spruce/Fir")) + 
  # add Fire Name labels
  geom_label_repel(aes(label = Fire_Name),
                   box.padding   = 0.35, 
                   point.padding = 0.5,
                   segment.color = 'grey50') + 
  
  theme_bw() + 
  # font size
  theme(axis.text.y = element_text(size=16),
        axis.title.y = element_text(size=16),
        axis.text.x = element_text(size=16),
        axis.title.x = element_text(size=16),
        # move the legend to the top of the figure
        legend.position="top") 

# Save figure to file
ggsave(filename = (here::here(file.path("figures",paste0(out_label,"-fire_size_vs_year_scatterplot.png")))),
       width = 7, height = 9)
```

